wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.10
      5: 0.10.26
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 10
ci:
  desc: null
  value: 0
client_num_in_total:
  desc: null
  value: 3
client_num_per_round:
  desc: null
  value: 3
client_optimizer:
  desc: null
  value: adam
comm_round:
  desc: null
  value: 600
data_dir:
  desc: null
  value: ./../../../data/Experiment_4/14_truncat
dataset:
  desc: null
  value: Experiment
epochs:
  desc: null
  value: 5
epochs_of_local_fine_tuning:
  desc: null
  value: 0
frequency_of_the_test:
  desc: null
  value: 2
gpu:
  desc: null
  value: 0
if_join_midway:
  desc: null
  value: true
join_epoch:
  desc: null
  value: 300
local_fine_tuning:
  desc: null
  value: false
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: lr
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero-fix
wd:
  desc: null
  value: 0.001
